(function(root){
  "use strict";
  var x='<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 6l12 12M18 6L6 18"/></svg>';
  var tick='<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12l4 4L19 6"/></svg>';
  function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function uid(){return crypto.randomUUID();}
  function localDate(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");}
  function dateValid(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
  function create(options){
    var model=null,overlay=null,card=null,controller=null,trigger=null,previousInert=[],generation=0,visualBusy=false,progress=false,calendar=null,openedAt=0;
    var unresolved=Object.create(null);
    function current(){return model&&options.scope()===model.scope;}
    function call(payload){return options.call(Object.assign({},payload,{budgetId:model.budgetId,userAccessId:options.userAccessId()}));}
    function picker(label,value,rows,field,key){var selected=rows.find(function(row){return row.id===value;});return '<label class="po-field">'+esc(label)+'<details class="po-picker"><summary>'+esc(selected?selected.label:"Choose…")+'</summary><div class="po-picker-menu"><input aria-label="Search '+esc(label)+'" placeholder="Search" data-po-search><div>'+rows.map(function(row){return '<button type="button" data-po-pick="'+esc(field)+'" data-key="'+esc(key||"")+'" data-value="'+esc(row.id)+'">'+esc(row.label)+'</button>';}).join('')+'</div></div></details></label>';}
    function field(label,value,name,key,readOnly){return '<label class="po-field">'+esc(label)+'<input data-po-field="'+name+'" data-key="'+esc(key||"")+'" value="'+esc(value)+'" '+(readOnly?'readonly':'')+' '+(/amount|Price|quantity|Amount/i.test(name)?'inputmode="decimal"':'')+'></label>';}
    function money(value){try{var negative=typeof value==='string'&&value[0]==='-';return (negative?'−$':'$')+root.LMPO.currency(root.LMPO.money(negative?value.slice(1):value));}catch(e){return '—';}}
    function patchTotal(){var total=0n;model.lines.forEach(function(line){try{total+=root.LMPO.money(line.finalAmount);}catch(ignore){}});var node=card.querySelector('.po-total');if(node)node.textContent='Lines '+money(root.LMPO.currency(total))+' · Header '+money(model.amount);}
    function mount(){
      overlay=document.createElement('div');overlay.className='po-overlay';overlay.innerHTML='<section class="po-card" role="dialog" aria-modal="true" aria-labelledby="po-title" aria-describedby="po-context" tabindex="-1"><header><div><h2 id="po-title">Purchase Order</h2><div id="po-context"></div></div><button class="po-x" data-po-close aria-label="Close Purchase Order">'+x+'</button></header><div class="po-body"></div><footer></footer></section>';
      document.body.appendChild(overlay);card=overlay.querySelector('.po-card');
      previousInert=Array.from(document.body.children).filter(function(node){return node!==overlay&&node.tagName!=='SCRIPT'&&node.tagName!=='STYLE';}).map(function(node){var old=node.inert;node.inert=true;return [node,old];});
      overlay.addEventListener('click',click);overlay.addEventListener('input',input);overlay.addEventListener('keydown',keydown);card.focus();
    }
    function close(){if(controller&&controller.state()&&controller.state().busy||visualBusy)return;generation++;if(controller&&controller.state()&&controller.state().unknown)unresolved[model.budgetId]={model:model,controller:controller};overlay.remove();previousInert.forEach(function(pair){pair[0].inert=pair[1];});overlay=null;model=null;progress=false;calendar=null;if(trigger&&trigger.isConnected)trigger.focus();}
    function keydown(event){if(event.key==='Escape'){event.preventDefault();event.stopPropagation();if(calendar){calendar=null;render();}else close();return;}if(event.key==='Tab'){var nodes=Array.from(card.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),summary,[tabindex="0"]')).filter(function(node){return node.getClientRects().length;});if(!nodes.length){event.preventDefault();card.focus();return;}var first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===card)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}
    function error(message){model.error=message;var el=card.querySelector('[data-po-error]');if(el){el.textContent=message;el.hidden=!message;}}
    function lineNew(){return {key:uid(),budgetItemId:'',description:'',costElement:'',pricingMode:'Calculated',quantity:null,unitPrice:null,finalAmount:null};}
    function render(){
      if(!overlay||progress)return;
      card.querySelector('#po-title').textContent='Purchase Order';
      var readOnly=model.status==='Submitted'||!model.editable,items=options.items().map(function(row){return {id:row.ID,label:(row.Budget_Code||'')+' · '+(row.Item_Name||row.Description||'Budget item')};});
      card.querySelector('#po-context').textContent=model.phase+(model.status?' · '+model.status:'');
      var html='<div class="po-error" data-po-error role="alert" '+(model.error?'':'hidden')+'>'+esc(model.error)+'</div>';
      html+='<div class="po-header-fields">'+picker('Vendor',model.vendorId,model.vendors.map(function(row){return {id:row.ID,label:row.Vendor_Name};}),'vendorId')+field('Full PO amount',model.amount,'amount')+field('Request date',model.requestDate,'requestDate')+field('Date needed',model.dateNeeded,'dateNeeded')+'</div>';
      html+='<div class="po-lines">'+model.lines.map(function(line,index){var manual=line.pricingMode==='Manual';return '<article class="po-line" data-line="'+esc(line.key)+'"><div class="po-line-head"><strong>Line '+(index+1)+'</strong><span>'+esc(line.pricingMode)+'</span>'+(!readOnly?'<button class="po-x" data-po-remove="'+esc(line.key)+'" aria-label="Remove line '+(index+1)+'">'+x+'</button>':'')+'</div><div class="po-line-fields">'+picker('Budget Item',line.budgetItemId,items,'budgetItemId',line.key)+picker('Cost Element',line.costElement,['1','2','3','4','5'].map(function(n){return {id:n,label:n};}),'costElement',line.key)+field('Description',line.description,'description',line.key)+field('Quantity',line.quantity,'quantity',line.key,manual)+field('Unit Price',line.unitPrice,'unitPrice',line.key,manual)+field('Final Amount',line.finalAmount,'finalAmount',line.key)+'</div>'+(!readOnly&&manual?'<button class="mbtn neutral" data-po-calculated="'+esc(line.key)+'">Use Quantity × Unit Price</button>':'')+'</article>';}).join('')+'</div>';
      var total=0n;model.lines.forEach(function(line){try{total+=root.LMPO.money(line.finalAmount);}catch(e){}});
      html+='<div class="po-total">Lines '+money(root.LMPO.currency(total))+' · Header '+money(model.amount)+'</div><div class="po-balances">'+(model.balanceState==='loaded'?balanceHtml():esc(model.balanceState==='loading'?'Checking balances…':'Budget balances unavailable'))+'</div>';
      if(calendar)html+=calendarHtml();
      card.querySelector('.po-body').innerHTML=html;
      card.querySelector('footer').innerHTML='<button class="mbtn neutral" data-po-refresh>Refresh balance</button><button class="mbtn neutral" data-po-saved>Saved POs</button>'+(!readOnly?'<button class="mbtn neutral" data-po-add>Add line</button><span class="po-spacer"></span><button class="mbtn neutral" data-po-save="Save">Save draft</button><button class="mbtn primary" data-po-save="Submit">Submit PO</button>':'<span class="po-spacer"></span><button class="mbtn neutral" data-po-close>Close</button>');
      if(readOnly)card.querySelectorAll('.po-body input,.po-body textarea,.po-picker').forEach(function(node){if(node.tagName==='DETAILS'){node.inert=true;}else node.readOnly=true;});
    }
    function balanceHtml(){var grouped={};model.lines.forEach(function(line){try{grouped[line.budgetItemId]=(grouped[line.budgetItemId]||0n)+root.LMPO.money(line.finalAmount);}catch(e){}});return Object.keys(grouped).map(function(id){var row=model.balances.find(function(b){return b.budgetItemId===id;}),item=options.items().find(function(i){return i.ID===id;});if(!row)return '<div>Availability unverified</div>';var available=BigInt(row.availableCents),remaining=available-grouped[id];return '<div class="po-receipt"><strong>'+esc(item&&item.Item_Name||'Budget Item')+'</strong><span>Available '+money(root.LMPO.currency(available))+'</span><span>Allocated '+money(root.LMPO.currency(grouped[id]))+'</span><span class="'+(remaining<0n?'po-error':'')+'">Remaining '+money(root.LMPO.currency(remaining))+'</span></div>';}).join('');}
    function calendarHtml(){var date=new Date(calendar.year,calendar.month,1),lead=date.getDay(),days=new Date(calendar.year,calendar.month+1,0).getDate(),cells='';for(var i=0;i<lead;i++)cells+='<span></span>';for(var n=1;n<=days;n++)cells+='<button data-po-day="'+localDate(new Date(calendar.year,calendar.month,n))+'">'+n+'</button>';return '<div class="po-calendar"><div><button data-po-month="-1" aria-label="Previous month">‹</button><strong>'+esc(date.toLocaleDateString('en-US',{month:'long',year:'numeric'}))+'</strong><button data-po-month="1" aria-label="Next month">›</button></div><div class="po-day-grid">'+cells+'</div></div>';}
    function input(event){
      if(!current()||progress||model.status==='Submitted'||!model.editable)return;
      var target=event.target;
      if(target.hasAttribute('data-po-search')){var needle=target.value.toLowerCase();target.parentElement.querySelectorAll('[data-po-pick]').forEach(function(button){button.hidden=button.textContent.toLowerCase().indexOf(needle)<0;});return;}
      var fieldName=target.dataset.poField;if(!fieldName)return;
      var line=model.lines.find(function(row){return row.key===target.dataset.key;});
      if(!line){model[fieldName]=target.value;patchTotal();return;}
      line[fieldName]=target.value;
      if(fieldName==='finalAmount'){line.pricingMode='Manual';line.quantity=null;line.unitPrice=null;var row=target.closest('.po-line');for(var f of ['quantity','unitPrice']){var node=row.querySelector('[data-po-field="'+f+'"]');node.value='';node.readOnly=true;}row.querySelector('.po-line-head span').textContent='Manual';if(!row.querySelector('[data-po-calculated]')){var btn=document.createElement('button');btn.className='mbtn neutral';btn.dataset.poCalculated=line.key;btn.textContent='Use Quantity × Unit Price';row.appendChild(btn);}}
      if(fieldName==='quantity'||fieldName==='unitPrice'){try{line.finalAmount=root.LMPO.multiply(line.quantity,line.unitPrice);}catch(e){line.finalAmount=null;}target.closest('.po-line').querySelector('[data-po-field="finalAmount"]').value=line.finalAmount||'';}
      card.querySelector('.po-balances').innerHTML=model.balanceState==='loaded'?balanceHtml():'Budget balances unavailable';
      patchTotal();
    }
    async function refresh(){var own=generation;model.balanceState='loading';render();try{var resp=await call({action:'Balances'});if(!current()||generation!==own)return;if(!resp||resp.contract!=='po-v1'||resp.success!==true||!Array.isArray(resp.balances))throw new Error(resp&&resp.error||'Availability cannot be verified.');var seen=new Set();resp.balances.forEach(function(b){if(typeof b.budgetItemId!=='string'||!/^\d+$/.test(b.budgetItemId)||seen.has(b.budgetItemId)||![b.finalCents,b.modCents,b.issuedCents,b.availableCents].every(function(n){return typeof n==='string'&&/^-?\d+$/.test(n);}))throw new Error('Malformed budget balance.');seen.add(b.budgetItemId);if(BigInt(b.finalCents)+BigInt(b.modCents)-BigInt(b.issuedCents)!==BigInt(b.availableCents))throw new Error('Budget balance does not reconcile.');});model.balances=resp.balances;model.balanceState='loaded';}catch(e){if(!current()||generation!==own)return;model.balanceState='unavailable';error(e.message);}render();}
    function mountProgress(){progress=true;openedAt=performance.now();card.querySelector('#po-title').textContent='Saving Purchase Order';card.querySelector('.po-body').innerHTML='<div class="po-total">'+esc(model.phase)+' → '+esc(model.vendorName||'Vendor')+' · '+money(model.amount)+' · '+model.lines.length+' lines</div><progress max="3" value="1" aria-label="Verified PO save stages"></progress><ol class="po-stages"><li>Validate PO <span>Done</span></li><li>Save header and lines <span>Running</span></li><li>Verify saved fields <span>Up next</span></li></ol><div class="po-error" data-po-error role="alert" hidden></div><div data-po-results></div>';card.querySelector('footer').innerHTML='<span data-po-status role="status" aria-live="polite">Saving header and lines…</span><span class="po-spacer"></span><button class="mbtn neutral" data-po-check hidden>Check saved PO</button><button class="mbtn neutral" data-po-done disabled>Close</button>';card.querySelector('[data-po-close]').disabled=true;card.focus();}
    function onState(run,stage){if(!overlay)return;var status=card.querySelector('[data-po-status]');if(!status)return;
      if(stage==='saving'||stage==='checking'){visualBusy=true;status.textContent=stage==='checking'?'Checking saved PO…':'Saving header and lines…';card.querySelector('[data-po-done]').disabled=true;card.querySelector('[data-po-close]').disabled=true;card.querySelector('[data-po-check]').disabled=true;}
      if(stage==='settled'){
        var wait=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.max(0,1120-(performance.now()-openedAt));
        setTimeout(function(){if(!overlay)return;visualBusy=false;card.querySelector('[data-po-done]').disabled=false;card.querySelector('[data-po-close]').disabled=false;card.querySelector('[data-po-check]').disabled=false;card.querySelector('[data-po-check]').hidden=!run.unknown;card.querySelector('[data-po-done]').textContent=run.snapshot?'Review PO':run.rejected?'Back to draft':'Close';
          var spans=card.querySelectorAll('.po-stages span');spans[1].textContent=run.snapshot?'Done':run.rejected?'Not saved':'Needs review';spans[2].textContent=run.snapshot?'Done':'Needs review';card.querySelector('progress').value=run.snapshot?3:1;
          status.textContent=run.snapshot?(run.snapshot.status==='Submitted'?'PO submitted · budget reserved':'Draft saved · no budget reserved'):run.rejected?'PO was not saved':'Saved state is unknown · use read-only Check';error(run.error);
          if(run.snapshot){unresolved[model.budgetId]=null;card.querySelector('[data-po-results]').innerHTML='<ul class="po-results">'+run.snapshot.lines.map(function(line){return '<li>'+tick+'<span>'+esc(line.description)+' · '+money(line.finalAmount)+' · Verified</span></li>';}).join('')+'</ul>';options.saved(run.snapshot);}
        },wait);
      }
    }
    async function save(action){if(progress||visualBusy||!current()||!model.editable||model.status==='Submitted')return;try{
      if(!dateValid(model.requestDate)||!dateValid(model.dateNeeded))throw new Error('Both dates must be valid YYYY-MM-DD dates.');
      var payload={action:action,id:model.id||'',expectedRevision:model.revision||'',budgetId:model.budgetId,vendorId:model.vendorId,amount:model.amount,requestDate:model.requestDate,dateNeeded:model.dateNeeded,lines:model.lines,token:uid(),userAccessId:options.userAccessId()};root.LMPO.validate(payload,action==='Submit');
      if(!model.vendors.some(function(v){return v.ID===model.vendorId;}))throw new Error('Select a verified Vendor.');
      if(action==='Submit'){if(model.balanceState!=='loaded')throw new Error('Refresh and verify budget availability before submitting.');var v=root.LMPO.validate(payload,true);for(var key of Object.keys(v.grouped)){var b=model.balances.find(function(row){return row.budgetItemId===key;});if(!b||v.grouped[key]>BigInt(b.availableCents))throw new Error('Grouped lines exceed available budget.');}}
      mountProgress();await controller.begin(payload);
    }catch(e){error(e.message);}}
    async function savedList(){var own=generation;try{var resp=await call({action:'List'});if(!current()||own!==generation)return;if(resp.contract!=='po-v1'||!resp.success||!Array.isArray(resp.rows))throw new Error(resp.error||'Saved POs unavailable.');card.querySelector('.po-body').innerHTML='<div data-po-error class="po-error" role="alert" hidden></div><div class="po-saved-list">'+resp.rows.map(function(row){if(typeof row.id!=='string'||!/^\d+$/.test(row.id))throw new Error('Invalid PO ID.');return '<button class="mbtn neutral" data-po-open="'+esc(row.id)+'">'+money(row.amount)+' · '+esc(row.status)+'</button>';}).join('')+'</div>';card.querySelector('footer').innerHTML='<button class="mbtn neutral" data-po-back>Back to draft</button>';}catch(e){error(e.message);}}
    async function get(id){var own=generation;try{var resp=await call({action:'Get',id:id});if(!current()||own!==generation)return;if(!resp||resp.contract!=='po-v1'||!resp.success||!resp.snapshot||resp.snapshot.id!==id||resp.snapshot.budgetId!==model.budgetId)throw new Error(resp&&resp.error||'PO could not be loaded.');if(!['Draft','Submitted'].includes(resp.snapshot.status)||resp.snapshot.commitmentState!==(resp.snapshot.status==='Submitted'?'Reserved':'None')||resp.snapshot.approvalState!=='Not Configured')throw new Error('Saved PO state could not be verified.');root.LMPO.validate(resp.snapshot,resp.snapshot.status==='Submitted');Object.assign(model,resp.snapshot);render();refresh();}catch(e){error(e.message);}}
    function click(event){var target=event.target.closest('button,input[data-po-field="requestDate"],input[data-po-field="dateNeeded"]');if(!target)return;
      if(target.hasAttribute('data-po-close')){close();return;}
      if(target.hasAttribute('data-po-done')){var run=controller.state();if(run&&run.snapshot){Object.assign(model,run.snapshot);progress=false;render();return;}if(run&&run.rejected){progress=false;render();return;}close();return;}
      if(target.hasAttribute('data-po-check')){if(!visualBusy){openedAt=performance.now();controller.check();}return;}
      if(progress||!current())return;
      if(target.hasAttribute('data-po-saved')){savedList();return;}if(target.dataset.poOpen){get(target.dataset.poOpen);return;}if(target.hasAttribute('data-po-back')){render();return;}if(target.hasAttribute('data-po-refresh')){refresh();return;}
      if(model.status==='Submitted'||!model.editable)return;
      if(target.dataset.poSave){save(target.dataset.poSave);return;}if(target.hasAttribute('data-po-add')){if(model.lines.length<100){model.lines.push(lineNew());render();}return;}
      if(target.dataset.poRemove){model.lines=model.lines.filter(function(line){return line.key!==target.dataset.poRemove;});render();return;}
      if(target.dataset.poCalculated){var at=model.lines.findIndex(function(l){return l.key===target.dataset.poCalculated;});model.lines[at]=root.LMPO.calculated(model.lines[at]);render();return;}
      if(target.dataset.poPick){var line=model.lines.find(function(l){return l.key===target.dataset.key;});(line||model)[target.dataset.poPick]=target.dataset.value;if(target.dataset.poPick==='vendorId')model.vendorName=target.textContent;render();return;}
      if(target.dataset.poField==='requestDate'||target.dataset.poField==='dateNeeded'){var d=dateValid(target.value)?new Date(target.value+'T12:00:00'):new Date();calendar={field:target.dataset.poField,year:d.getFullYear(),month:d.getMonth()};render();return;}
      if(target.dataset.poMonth){var date=new Date(calendar.year,calendar.month+Number(target.dataset.poMonth),1);calendar.year=date.getFullYear();calendar.month=date.getMonth();render();return;}
      if(target.dataset.poDay){model[calendar.field]=target.dataset.poDay;calendar=null;render();}
    }
    async function open(budget,source){if(overlay)return;trigger=source||document.activeElement;generation++;var pending=unresolved[String(budget.ID)];
      if(pending){if(pending.model.scope!==options.scope())throw new Error('An unresolved PO belongs to another Creator session. Review that operation before opening a new draft.');model=pending.model;controller=pending.controller;mount();mountProgress();onState(controller.state(),'settled');return;}
      model={budgetId:String(budget.ID),phase:options.phaseName(budget),scope:options.scope(),editable:options.canEdit(budget),amount:'',vendorId:'',requestDate:localDate(new Date()),dateNeeded:'',lines:[lineNew()],vendors:[],balances:[],balanceState:'loading',error:''};
      controller=root.LMPOController.create({call:call,onState:onState});mount();render();var own=generation;
      try{var vendors=await options.vendors();if(!current()||own!==generation)return;var seen=new Set();vendors.forEach(function(row){if(typeof row.ID!=='string'||!/^\d+$/.test(row.ID)||seen.has(row.ID))throw new Error('Vendor identity is unavailable.');seen.add(row.ID);});model.vendors=vendors;render();}catch(e){if(current())error(e.message);}
      if(current())refresh();
    }
    return {open:open,isOpen:function(){return !!overlay;}};
  }
  root.LMPOUI={create:create};
})(typeof globalThis!=="undefined"?globalThis:this);
