/* Host integration for the relocated spreadsheet workflow. */
(function(root){
root.LMLotImport={mount:function(ctx){
var CFG={version:ctx.version,pageSize:200,maxPages:50,customApis:{platIngest:'Ingest_Plat'}};
var S={plat:{confirmResolve:null}},$=id=>document.getElementById(id),str=v=>v==null?'':String(v),esc=v=>str(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),auditLog=ctx.log;
    var LOT_CITIES=["Killeen","Houston","Granger","Caldwell","Temple","Waco","Bryan","Belton","Bruceville-Eddy","Copperas Cove","Seguin","Harker Heights","Taylor","New Braunfels","Jarrell","Troy","Nolanville","Robinson","Salado","Pflugerville","San Antonio","Georgetown","Lorena","Addison","Balch Springs","Carrollton","Cedar Hill","Cockrell Hill","Combine","Coppell","Dallas","DeSoto","Duncanville","Farmers Branch","Ferris","Garland","Glenn Heights","Grand Prairie","Grapevine","Highland Park","Hutchins","Irving","Lancaster","Lewisville","Mesquite","Ovilla","Richardson","Rowlett","Sachse","Seagoville","Sunnyvale","University Park","Wilmer","Wylie","League City","Pasadena","Pearland","Sugar Land","Conroe","Katy","Denton","Sherman","Westminster","Anna","Crandall","Midlothian","Celina","Van Alstyne","Greenville","Princeton","Corsicana","Waxahachie","Prosper","Cresson"];
    var LOT_COUNTIES=["Bell","Bexar","McLennan","Brazos","Falls","Williamson","Coryell","Guadalupe","Comal","Burleson","Harris","Grayson","Collin","Tarrant","Johnson","Kaufman","Ellis","Denton","Hunt","Dallas","Cooke","Navarro"];
function errText(e){if(!e)return"Unknown error";if(typeof e==="string")return e;return e.message||e.responseText||JSON.stringify(e).slice(0,300)}
function safeStringify(o){if(o==null)return"";if(typeof o==="string")return o.length>12000?o.slice(0,12000)+"…(truncated)":o;var seen=[];try{var t=JSON.stringify(o,function(k,v){if(typeof v==="object"&&v!==null){if(seen.indexOf(v)>=0)return"[circular]";seen.push(v)}if(typeof v==="string"&&v.length>6000)return v.slice(0,6000)+"…";return v});return t&&t.length>12000?t.slice(0,12000)+"…(truncated)":(t||"")}catch(e){try{return String(o)}catch(e2){return"[unstringifiable]"}}}
function responseBad(r){var c=r&&(r.code||(r.result&&r.result.code));return !r||(c&&String(c)!=="3000")||r.error||(r.result&&r.result.error)}
function sdkResponseInfo(value){var out={type:typeof value,keys:value&&typeof value==="object"?Object.keys(value).slice(0,12):[],code:"",codePath:"",message:""};function visit(v,path,depth){if(out.code||depth>5||v==null)return;if(typeof v==="string"){if(v.length<10000)try{visit(JSON.parse(v),path+".json",depth+1)}catch(ignore){}return}if(typeof v!=="object")return;if(v.code!=null){out.code=String(v.code);out.codePath=path+".code";out.message=String(v.message||"").slice(0,200);return}["result","responseText","error","message","response","details"].forEach(function(k){if(v[k]!=null)visit(v[k],path+"."+k,depth+1)})}visit(value,"root",0);return out}
function emptyResponse(r){var c=sdkResponseInfo(r).code;return c==="3100"||c==="9280"}
function getAll(report,criteria,pageLimit){var out=[];var maxPages=pageLimit||CFG.maxPages;function page(n){var a={reportName:report,page:n,pageSize:CFG.pageSize},started=Date.now();if(criteria)a.criteria=criteria;var detail={report:report,criteria:criteria||"(all records)",page:n,pageSize:CFG.pageSize,version:CFG.version};auditLog("info","Creator report request",detail);return Promise.resolve().then(function(){return ZOHO.CREATOR.API.getAllRecords(a)}).then(function(r){var info=sdkResponseInfo(r);auditLog(emptyResponse(r)?"info":responseBad(r)?"error":"success","Creator report response",Object.assign({},detail,info,{elapsedMs:Date.now()-started,rows:Array.isArray(r&&r.data)?r.data.length:0,empty:emptyResponse(r)}));if(emptyResponse(r))return out;if(responseBad(r))throw r;var rows=r.data||[];out=out.concat(rows);if(rows.length===CFG.pageSize){if(n>=maxPages)throw new Error("The "+report+" result is incomplete. Narrow the selected subdivision scope.");return page(n+1)}return out},function(e){var info=sdkResponseInfo(e),empty=emptyResponse(e);auditLog(empty?"info":"error",empty?"Creator empty result (rejected response)":"Creator report request failed",Object.assign({},detail,info,{elapsedMs:Date.now()-started,empty:empty,errorPreview:String(safeStringify(e)||"").slice(0,500)}));if(empty)return out;throw e})}return page(1)}
function unwrapApi(r){var v=r,guard=0;while(v&&typeof v==="object"&&guard++<6){if(v.details&&typeof v.details==="object"&&"output" in v.details){v=v.details.output;continue}if("output" in v&&!("success" in v)){v=v.output;continue}if("result" in v&&!("success" in v)){v=v.result;continue}if("data" in v&&!("success" in v)){v=v.data;continue}break}if(typeof v==="string"){var s=v.trim();if(/^[\[{]/.test(s))try{v=JSON.parse(s)}catch(e){}}return v}
function platInvoke(body){var api=LMRuntime.apiName(CFG.customApis.platIngest),z=window.ZOHO&&ZOHO.CREATOR,fn=z&&((z.API&&typeof z.API.invokeCustomApi==="function"&&z.API.invokeCustomApi.bind(z.API))||(z.DATA&&typeof z.DATA.invokeCustomApi==="function"&&z.DATA.invokeCustomApi.bind(z.DATA)));var summary={api:api,mode:body.mode,tile:body.tileIndex,of:body.tileCount,page:body.page,row:body.row,col:body.col,imageBytes:body.image?body.image.length:0,overviewBytes:body.overview?body.overview.length:0,textLabels:body.textCount||0,payloadBytes:JSON.stringify(body).length,via:z&&z.API&&z.API.invokeCustomApi?"API.invokeCustomApi":z&&z.DATA&&z.DATA.invokeCustomApi?"DATA.invokeCustomApi":"none"};auditLog("info","Plat API call",summary);if(!fn){auditLog("error","Plat API unavailable — the Creator SDK exposes no invokeCustomApi",summary);return Promise.reject(new Error("invokeCustomApi unavailable"))}var t0=Date.now();return fn({api_name:api,http_method:"POST",content_type:"application/json",payload:{payload:JSON.stringify(body)}}).then(function(r){var ms=Date.now()-t0,c=r&&(r.code||(r.result&&r.result.code));if(c&&String(c)!=="3000"){var err=new Error(errText(r));err.code=c;err.raw=r;err.api=api;auditLog("warn","Plat API returned code "+c,{api:api,mode:body.mode,tile:body.tileIndex,ms:ms,response:safeStringify(r).slice(0,4000)});throw err}var out=unwrapApi(r);if(!out||typeof out!=="object"){var e1=new Error("The plat import API returned nothing readable.");e1.raw=r;e1.api=api;auditLog("warn","Plat API response unreadable",{api:api,mode:body.mode,tile:body.tileIndex,ms:ms,response:safeStringify(r).slice(0,4000)});throw e1}if(out.success!==true&&String(out.success)!=="true"){var e2=new Error(str(out.error)||"The plat import API reported a failure.");e2.api=api;e2.raw=out;auditLog("warn","Plat API reported failure",{api:api,mode:body.mode,tile:body.tileIndex,ms:ms,error:str(out.error),response:safeStringify(out).slice(0,4000)});throw e2}auditLog("success","Plat API ok",{api:api,mode:body.mode,tile:body.tileIndex,ms:ms,rows:Array.isArray(out.rows)?out.rows.length:undefined,kind:out.kind,model:out.model,provider:out.provider});return out},function(e){var ms=Date.now()-t0;auditLog("warn","Plat API call rejected by the SDK",{api:api,mode:body.mode,tile:body.tileIndex,ms:ms,error:errText(e),detail:safeStringify(e).slice(0,4000)});throw e})}
function piConfirm(o){return new Promise(function(res){var prior=document.activeElement;var el=$("piConfirm"),done=function(v){el.classList.remove("open");el.innerHTML="";el.onclick=null;S.plat.confirmResolve=null;if(prior&&prior.isConnected)prior.focus();res(!!v)};el.innerHTML='<div class="pi-cbox"><div class="pi-ch"><div class="pi-ck">'+esc(o.kicker||"Confirm")+'</div><h3>'+esc(o.title||"Are you sure?")+'</h3></div><div class="pi-cb">'+(o.message?esc(o.message):'')+(o.items&&o.items.length?'<ul>'+o.items.map(function(t){return'<li>'+esc(t)+'</li>'}).join("")+'</ul>':'')+'</div><div class="pi-cf"><button type="button" class="btn" data-pi-c="0">'+esc(o.cancelLabel||"Cancel")+'</button><button type="button" class="btn '+(o.danger?'danger':'primary')+'" data-pi-c="1">'+esc(o.okLabel||"Continue")+'</button></div></div>';el.classList.add("open");el.onclick=function(e){var b=e.target.closest("[data-pi-c]");if(b)done(b.dataset.piC==="1")};S.plat.confirmResolve=done;var ok=el.querySelector('[data-pi-c="1"]');if(ok)ok.focus()})}
function readSubdivisionLots(sid){if(!/^\d+$/.test(String(sid)))return Promise.reject(new Error('Subdivision ID is invalid.'));return Promise.all(['All_Lots_All_Fields','All_Active_Lots_List_View'].map(report=>getAll(report,'(Subdivision == '+sid+')'))).then(groups=>{var byId=new Map();groups.forEach(rows=>rows.forEach(l=>{var id=String(l.ID);byId.set(id,Object.assign({},byId.get(id)||{},l))}));return Array.from(byId.values())});}
var spreadsheet=LMSpreadsheetImport.mount({subdivisions:ctx.subdivisions,selected:ctx.selected,cities:LOT_CITIES,counties:LOT_COUNTIES,invoke:platInvoke,readLots:readSubdivisionLots,add:ctx.add,reload:ctx.reload,error:errText,confirm:piConfirm,log:auditLog});
$('platImport').addEventListener('click',function(){if(!ctx.live()){ctx.unavailable();return;}if(ctx.prepare)ctx.prepare();spreadsheet.open();});
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&S.plat.confirmResolve){e.preventDefault();S.plat.confirmResolve(false)}});
$('piConfirm').addEventListener('keydown',function(e){if(e.key!=='Tab')return;var buttons=this.querySelectorAll('button');if(buttons.length){e.preventDefault();(document.activeElement===buttons[0]?buttons[1]:buttons[0]).focus()}});
return spreadsheet;
}};
})(window);
