(function(root){
  "use strict";
  var x='<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 6l12 12M18 6L6 18"/></svg>';
  var tick='<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12l4 4L19 6"/></svg>';
  function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function uid(){return crypto.randomUUID();}
  function localDate(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");}
  function dateValid(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
  function create(options){
    var model=null,overlay=null,card=null,controller=null,trigger=null,previousInert=[],generation=0,visualBusy=false,progress=false,openedAt=0,popover=null;
    var unresolved=Object.create(null);
    function current(){return model&&options.scope()===model.scope;}
    function call(payload){return options.call(Object.assign({},payload,{budgetId:model.budgetId,userAccessId:options.userAccessId()}));}
    var chevron='<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="m7 10 5 5 5-5"/></svg>';
    var duplicateIcon='<svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>';
    function readOnly(){return model.status==='Submitted'&&model.approvalState!=='Rejected'||!model.editable;}
    function picker(label,value,rows,field,key){var selected=rows.find(function(row){return row.id===value;});return '<label class="po-field"><span>'+esc(label)+'</span><button type="button" class="po-picker-trigger'+(!selected?' is-placeholder':'')+'" data-po-picker="'+esc(field)+'" data-key="'+esc(key||'')+'" aria-haspopup="listbox" aria-expanded="false" aria-label="'+esc(label)+'" '+(readOnly()?'disabled':'')+'><span>'+esc(selected?selected.label:field==='uom'?'Unit':'Choose…')+'</span>'+chevron+'</button></label>';}
    function field(label,value,name,key,locked){return '<label class="po-field"><span>'+esc(label)+'</span><input aria-label="'+esc(label)+'" data-po-field="'+name+'" data-key="'+esc(key||'')+'" value="'+esc(value)+'" '+(locked||readOnly()?'readonly':'')+' '+(/amount|Price|quantity|Amount/i.test(name)?'inputmode="decimal"':'')+'></label>';}
    function money(value){try{var negative=typeof value==='string'&&value[0]==='-';var exact=root.LMPO.currency(root.LMPO.money(negative?value.slice(1):value)),parts=exact.split('.');return (negative?'−$':'$')+parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,',')+(parts[1]==='00'?'':'.'+parts[1]);}catch(e){return '—';}}
    function totals(){var total=0n;model.lines.forEach(function(line){try{total+=root.LMPO.money(line.finalAmount);}catch(ignore){}});return total;}
    function patchTotal(){var total=totals();model.amount=root.LMPO.currency(total);card.querySelector('[data-po-total]').textContent=money(model.amount);overlay.querySelector('[data-po-summary-total]').textContent=money(model.amount);}
    function dateField(label,value,name){return '<label class="po-field"><span>'+esc(label)+'</span><div class="request-date-shell"><input aria-label="'+esc(label)+'" data-po-date="'+name+'" value="'+esc(value)+'" placeholder="YYYY-MM-DD" readonly aria-haspopup="dialog" aria-expanded="false" '+(readOnly()?'disabled':'')+'><button type="button" class="request-date-open" data-po-date="'+name+'" aria-label="Choose '+esc(label)+'" aria-haspopup="dialog" aria-expanded="false" '+(readOnly()?'disabled':'')+'><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3v4M17 3v4M4 9h16M5 5h14a1 1 0 0 1 1 1v14H4V6a1 1 0 0 1 1-1Z"/></svg></button></div></label>';}
    function itemRows(selectable){
      var own=Object.create(null);
      model.reservedLines.forEach(function(line){own[line.budgetItemId]=(own[line.budgetItemId]||0n)+root.LMPO.money(line.finalAmount);});
      return options.items().map(function(row){
        var balance=model.balanceState==='loaded'&&model.balances.find(function(b){return b.budgetItemId===row.ID;});
        var code=row.Budget_Code||(balance&&balance.subdivisionCode&&balance.minorCode?balance.subdivisionCode+'-'+balance.minorCode:row.Cost_Code);
        var minor=String(balance&&balance.minorCode||row.Cost_Code||String(code||'').split('-').pop()||''),major=String(row.Major_Code||(/^\d+$/.test(minor)?minor[0]+'000':''));
        var category=options.itemCategory?options.itemCategory(row):{id:'',name:'Uncategorized'};
        var name=row.Item_Name||row.Description||'Budget item';
        return {id:row.ID,label:(code?code+' · ':'')+name,name:name,code:String(code||''),minorCode:minor,majorCode:major,categoryId:category.id,categoryName:category.name||'Uncategorized',excluded:/^[89]\d*$/.test(minor)||/^(8000|9000)$/.test(major)||/^40\d{2}$/.test(minor),modified:balance?BigInt(balance.finalCents)+BigInt(balance.modCents):null,available:balance?BigInt(balance.availableCents)+(own[row.ID]||0n):null};
      }).filter(function(row){return !selectable||!row.excluded&&row.modified!==null&&row.modified!==0n;}).sort(function(a,b){if(!a.code!==!b.code)return a.code?-1:1;return a.code.localeCompare(b.code,undefined,{numeric:true,sensitivity:'base'})||a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'});});
    }

    function closePopover(){if(!popover)return;var trigger=popover.trigger;if(popover.date){options.closeDate();}else popover.element.remove();popover=null;if(trigger&&trigger.isConnected){trigger.setAttribute('aria-expanded','false');trigger.focus();}}
    function optionHtml(row,name,value,key){return '<button type="button" role="option" aria-selected="'+(row.id===value)+'" data-po-pick="'+esc(name)+'" data-key="'+esc(key||'')+'" data-value="'+esc(row.id)+'" data-po-search-text="'+esc([row.label,row.majorCode,row.categoryName].join(' ').toLowerCase())+'"><span class="po-option-content"><span class="po-option-name" title="'+esc(row.label)+'">'+(name==='budgetItemId'?'<span class="po-cost-pill">'+esc(row.code||'—')+'</span><span class="po-item-name">'+esc(row.name)+'</span>':esc(row.label))+'</span>'+(name==='budgetItemId'?'<span class="po-option-balances"><span><span class="po-option-metric-label">Modified budget </span><strong>'+money(root.LMPO.currency(row.modified))+'</strong></span><span><span class="po-option-metric-label">After existing POs </span><strong'+(row.available<0n?' class="is-negative"':'')+'>'+money(root.LMPO.currency(row.available))+'</strong></span></span>':'')+'</span><span class="po-selection">'+(row.id===value?tick:'')+'</span></button>';}
    function openPopover(target){
      closePopover();var line=model.lines.find(function(row){return row.key===target.dataset.key;}),el=document.createElement('div'),name=target.dataset.poPicker;el.className='po-popover';
      var rows=name==='vendorId'?model.vendors.map(function(v){return {id:v.ID,label:v.Vendor_Name};}):name==='uom'?root.LMPO.uoms.map(function(n){return {id:n,label:n};}):name==='costElement'?['1','2','3','4','5'].map(function(n){return {id:n,label:n};}):itemRows(true),value=(line||model)[name],content='';
      if(name==='budgetItemId'){
        el.classList.add('po-item-popover');var groups=new Map();rows.forEach(function(row){var key=row.majorCode+'|'+row.categoryId+'|'+row.categoryName;if(!groups.has(key))groups.set(key,{major:row.majorCode,category:row.categoryName,rows:[]});groups.get(key).rows.push(row);});
        content='<div class="po-item-column-head" aria-hidden="true"><span>Cost code / item</span><span>Modified budget</span><span>After existing POs</span><span></span></div>'+Array.from(groups.values()).map(function(group){return '<div class="po-item-group"><div class="po-item-group-title"><strong>'+esc(group.major||'Other')+'</strong><span>'+esc(group.category)+'</span></div>'+group.rows.map(function(row){return optionHtml(row,name,value,target.dataset.key);}).join('')+'</div>';}).join('');
      }else content=rows.map(function(row){return optionHtml(row,name,value,target.dataset.key);}).join('');
      el.innerHTML=(name==='costElement'?'':'<input aria-label="Search '+esc(name==='uom'?'UOM':name==='vendorId'?'Vendor':'Budget Item')+'" placeholder="Search…" data-po-search>')+'<div role="listbox" aria-label="'+esc(name)+'">'+content+'</div><div class="po-picker-empty" data-po-picker-empty '+(rows.length?'hidden':'')+'>'+(name==='budgetItemId'?(model.balanceState==='loading'?'Checking item budgets…':model.balanceState!=='loaded'?'Item budgets unavailable':'No eligible budget items.'):'No options available.')+'</div>';
      target.setAttribute('aria-expanded','true');overlay.appendChild(el);popover={element:el,trigger:target};var rect=target.getBoundingClientRect(),width=Math.min(Math.max(name==='costElement'?110:name==='budgetItemId'?860:280,rect.width),window.innerWidth-24);el.style.width=width+'px';el.style.left=Math.max(12,Math.min(rect.left,window.innerWidth-width-12))+'px';el.style.top=Math.max(12,Math.min(rect.bottom+7,window.innerHeight-el.offsetHeight-12))+'px';(el.querySelector('input')||el.querySelector('[aria-selected=true]')||el.querySelector('[role=option]')).focus();
    }
    function openDate(target){closePopover();var fieldName=target.dataset.poDate,input=target.closest('.request-date-shell').querySelector('input');if(!options.openDate){error('Date picker unavailable. Reload Budget Manager.');return;}var element=options.openDate(input,function(value){model[fieldName]=value;render();card.querySelector('input[data-po-date="'+fieldName+'"]').focus({preventScroll:true});},function(){popover=null;if(input.isConnected)input.focus({preventScroll:true});});popover={date:true,element:element,trigger:target};}
    function mount(){
      overlay=document.createElement('div');overlay.className='po-overlay';overlay.innerHTML='<div class="po-workspace" role="dialog" aria-modal="true" aria-labelledby="po-title" aria-describedby="po-context"><section class="po-card" tabindex="-1"><header><div><h2 id="po-title">Purchase Order</h2><div id="po-context"></div></div><button class="po-x" data-po-close aria-label="Close Purchase Order">'+x+'</button></header><div class="po-body"></div><footer></footer></section><aside class="po-summary" aria-labelledby="po-summary-title"><header><h2 id="po-summary-title">Summary</h2><span data-po-summary-count></span></header><div class="po-summary-body" data-po-summary></div><footer><span>TOTAL</span><strong data-po-summary-total></strong></footer></aside></div>';
      document.body.appendChild(overlay);card=overlay.querySelector('.po-card');
      previousInert=Array.from(document.body.children).filter(function(node){return node!==overlay&&node.tagName!=='SCRIPT'&&node.tagName!=='STYLE';}).map(function(node){var old=node.inert;node.inert=true;return [node,old];});
      overlay.addEventListener('click',click);overlay.addEventListener('input',input);overlay.addEventListener('keydown',keydown);card.focus();
    }
    function close(){if(controller&&controller.state()&&controller.state().busy||visualBusy)return;generation++;if(controller&&controller.state()&&controller.state().unknown)unresolved[model.budgetId]={model:model,controller:controller};closePopover();overlay.remove();previousInert.forEach(function(pair){pair[0].inert=pair[1];});overlay=null;model=null;progress=false;if(trigger&&trigger.isConnected)trigger.focus();}
    function keydown(event){if(!popover&&!readOnly()&&event.target.dataset.poDate&&(event.key==='Enter'||event.key==='ArrowDown')){event.preventDefault();openDate(event.target);return;}if(popover&&!popover.date&&(event.key==='ArrowDown'||event.key==='ArrowUp')){event.preventDefault();var choices=Array.from(popover.element.querySelectorAll('[role=option]:not([hidden])'));var at=choices.indexOf(document.activeElement);if(choices.length)choices[(at+(event.key==='ArrowDown'?1:-1)+choices.length)%choices.length].focus();return;}if(event.key==='Escape'){event.preventDefault();event.stopPropagation();if(popover){closePopover();}else close();return;}if(event.key==='Tab'){var nodes=Array.from((popover?popover.element:overlay).querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),summary,[tabindex="0"]')).filter(function(node){return node.getClientRects().length;});if(!nodes.length){event.preventDefault();card.focus();return;}var first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===card)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}
    function error(message){model.error=message;var el=card.querySelector('[data-po-error]');if(el){el.textContent=message;el.hidden=!message;}}
    function lineNew(){return {key:uid(),budgetItemId:'',description:'',uom:'',costElement:'5',pricingMode:'Calculated',quantity:null,unitPrice:null,finalAmount:null};}
    function render(){
      if(!overlay||progress)return;
      closePopover();
      overlay.querySelector('.po-summary').hidden=false;
      card.querySelector('#po-title').textContent='Purchase Order';
      var locked=readOnly(),items=itemRows();
      card.querySelector('#po-context').textContent=model.phase;
      var html='<div class="po-error" data-po-error role="alert" '+(model.error?'':'hidden')+'>'+esc(model.error)+'</div>';
      html+='<div class="po-header-fields">'+picker('Vendor',model.vendorId,model.vendors.map(function(row){return {id:row.ID,label:row.Vendor_Name};}),'vendorId')+dateField('Request date',model.requestDate,'requestDate')+dateField('Date needed',model.dateNeeded,'dateNeeded')+'</div>';
      html+='<div class="po-ledger-title"><h3>Line items</h3><span>'+model.lines.length+' / 100</span><span class="po-spacer"></span><span class="po-draft-chip">'+esc(model.approvalState&&model.approvalState!=='Not Configured'?model.approvalState:model.status||'Draft')+'</span></div><div class="po-ledger-scroll"><div class="po-ledger-head"><span>Cost code / budget item</span><span>Description</span><span>Qty</span><span>UOM</span><span>Element</span><span>Unit price</span><span>Total</span><span></span></div>';
      html+='<div class="po-lines">'+model.lines.map(function(line,index){var manual=line.pricingMode==='Manual';return '<article class="po-line" data-line="'+esc(line.key)+'"><div class="po-line-fields"><div class="po-code-cell">'+picker('Budget Item',line.budgetItemId,items.map(function(item){return {id:item.id,label:item.id===line.budgetItemId?(lineCode(line)||item.label):item.label};}),'budgetItemId',line.key)+'</div>'+field('Description',line.description,'description',line.key)+field('Quantity',line.quantity,'quantity',line.key,manual)+picker('UOM',line.uom,root.LMPO.uoms.map(function(n){return {id:n,label:n};}),'uom',line.key)+picker('Cost Element',line.costElement,['1','2','3','4','5'].map(function(n){return {id:n,label:n};}),'costElement',line.key)+field('Unit Price',line.unitPrice,'unitPrice',line.key,manual)+field('Final Amount',line.finalAmount,'finalAmount',line.key)+'<div class="po-line-actions">'+(!locked?'<button class="po-duplicate" data-po-duplicate="'+esc(line.key)+'" title="Duplicate line" aria-label="Duplicate line '+(index+1)+'" '+(model.lines.length>=100?'disabled':'')+'>'+duplicateIcon+'</button><button class="po-x po-remove" data-po-remove="'+esc(line.key)+'" aria-label="Remove line '+(index+1)+'">'+x+'</button>':'')+'</div></div><div class="po-line-meta"><span data-po-mode>'+ (manual?'Manual amount':'')+'</span><button class="po-link" data-po-calculated="'+esc(line.key)+'" '+(manual&&!locked?'':'hidden')+'>Use quantity × price</button></div></article>';}).join('')+'</div></div>';
      if(!locked)html+='<div class="po-add-actions"><button class="po-add" data-po-add="1"><span aria-hidden="true">+</span> Add line</button><button class="po-add" data-po-add="10">+ 10 lines</button></div>';
      html+='<div class="po-total"><span>TOTAL</span><strong data-po-total></strong></div>';
      if(model.approvalBundle)html+=bundleHtml();
      card.querySelector('.po-body').innerHTML=html;
      card.querySelector('footer').innerHTML='<button class="mbtn neutral" data-po-saved>Saved POs</button><button class="po-link" data-po-refresh>Refresh balances</button><span class="po-spacer"></span>'+(!locked?'<button class="mbtn neutral" data-po-save="Save">Save draft</button><button class="mbtn primary" data-po-save="Submit">'+(model.approvalState==='Rejected'?'Resubmit PO':'Submit PO')+'</button>':'<button class="mbtn neutral" data-po-close>Close</button>');
      if(model.approvalBundle&&model.approvalBundle.canApprove&&model.approvalState==='Pending'){card.querySelector('footer').insertAdjacentHTML('beforeend','<button class="mbtn neutral" data-po-decision="Reject">Reject PO</button><button class="mbtn primary" data-po-decision="Approve">Approve PO &amp; mods</button>');}
      if(model.approvalBundle&&model.approvalBundle.canRetryEmail&&model.approvalState==='Pending'&&!model.approvalBundle.emailSent){card.querySelector('footer').insertAdjacentHTML('beforeend','<button class="mbtn neutral" data-po-decision="RetryEmail">Retry email</button>');}
      patchBalances();
      patchTotal();
    }
    function bundleHtml(){var bundle=model.approvalBundle;return '<section class="po-approval-bundle"><div class="po-ledger-title"><h3>Approval chain</h3><span class="po-spacer"></span><span>'+esc(model.approvalState)+'</span></div><div class="po-approval-steps">'+bundle.rows.map(function(row){return '<div><span class="po-step-order">'+esc(row.order)+'</span><strong>'+esc(row.role)+'</strong><span>'+esc(row.status)+'</span>'+(row.notes?'<p>'+esc(row.notes)+'</p>':'')+'</div>';}).join('')+'</div>'+bundle.modifications.map(function(mod){var item=options.items().find(function(row){return row.ID===mod.budgetItemId;});return '<div class="po-bundle-mod"><span>'+esc(item&&item.Item_Name||'Budget item')+'</span><strong>+'+money(mod.amount)+'</strong><span>'+esc(mod.status)+'</span></div>';}).join('')+(bundle.canApprove&&model.approvalState==='Pending'?'<label class="po-field po-decision-note"><span>Approval notes</span><textarea aria-label="Approval notes" data-po-approval-note maxlength="9000">'+esc(model.approvalNote||'')+'</textarea></label>':'')+'</section>';}
    async function decide(action){if(progress||visualBusy||!current()||!model.approvalBundle)return;var bundle=model.approvalBundle;if(action==='RetryEmail'?!bundle.canRetryEmail:!bundle.canApprove)return;var note=(bundle.active.notes?bundle.active.notes+'\n\n':'')+(model.approvalNote||'').trim();mountProgress(action);await controller.decide({action:action,id:model.id,budgetId:model.budgetId,approvalId:bundle.active.id,expectedRevision:model.revision,note:note,userAccessId:options.userAccessId()});}
    function lineCode(line){if(readOnly()&&line.costCode)return line.costCode;var balance=model.balances.find(function(row){return row.budgetItemId===line.budgetItemId;});return balance?root.LMPO.costCode(balance.subdivisionCode,balance.minorCode,line.costElement):(line.costCode||'');}
    function allocationRows(){return root.LMPO.allocations(model.lines,model.balances,model.reservedLines,model.approvalBundle&&model.approvalBundle.modifications);}
    function summaryRows(){
      var allocations=allocationRows(), groups=new Map();
      model.lines.forEach(function(line){if(!line.budgetItemId)return;var code=lineCode(line),key=line.budgetItemId+'|'+code;if(!groups.has(key))groups.set(key,{budgetItemId:line.budgetItemId,code:code,count:0});groups.get(key).count++;});
      return Array.from(groups.values()).map(function(group){var allocation=allocations.find(function(row){return row.budgetItemId===group.budgetItemId;}),balance=model.balances.find(function(row){return row.budgetItemId===group.budgetItemId;}),item=options.items().find(function(row){return row.ID===group.budgetItemId;});return Object.assign(group,{label:item&&(item.Item_Name||item.Description)||'Budget item',allocation:allocation,modified:balance?BigInt(balance.finalCents)+BigInt(balance.modCents):null,shared:Array.from(groups.values()).filter(function(row){return row.budgetItemId===group.budgetItemId;}).length>1});}).sort(function(a,b){return a.code.localeCompare(b.code,undefined,{numeric:true,sensitivity:'base'});});
    }
    function patchBalances(){
      var rows=summaryRows(),node=overlay.querySelector('[data-po-summary]');
      overlay.querySelector('[data-po-summary-count]').textContent=rows.length+' '+(rows.length===1?'cost code':'cost codes');
      node.innerHTML='<div class="po-summary-scroll" tabindex="0" aria-label="Cost code budget summary"><table><thead><tr><th>Cost code</th><th>Modified budget</th><th>Existing POs</th><th>Available</th><th title="All current PO lines for the budget item">This PO</th><th>Remaining</th></tr></thead><tbody>'+rows.map(function(row){var a=row.allocation,verified=model.balanceState==='loaded'&&a&&a.verified;var values=verified?[row.modified,row.modified-a.available,a.available,a.allocated,a.remaining]:[];var hint=verified?[(a.pending>0n?'Other PO mods pending +'+money(root.LMPO.currency(a.pending)):''),(a.shortfall>0n?'Automatic modification +'+money(root.LMPO.currency(a.shortfall)):'')].filter(Boolean).join(' · '):model.balanceState==='loading'?'Checking balance…':'Balance unavailable';return '<tr title="'+esc(row.label+(row.shared?' · Shared item budget: This PO and Remaining include every line using this item.':'')+(hint?' · '+hint:''))+'"><th scope="row"><strong>'+esc(row.code||row.label)+'</strong>'+(row.shared?'<span class="po-shared">Shared</span>':'')+'</th>'+[0,1,2,3,4].map(function(index){return '<td class="'+(index===4?(verified&&a.remaining<0n?'is-negative':'is-remaining'):'')+'">'+(verified?((index===1||index===3)&&values[index]>0n?'− ':'')+money(root.LMPO.currency(values[index])):'—')+'</td>';}).join('')+'</tr>'+(hint?'<tr class="po-summary-hint"><td colspan="6">'+esc(hint)+'</td></tr>':'');}).join('')+'</tbody></table>'+(rows.length?'':'<div class="po-summary-empty">Choose a budget item.</div>')+'</div>';
      overlay.querySelector('[data-po-summary-total]').textContent=money(root.LMPO.currency(totals()));
    }
    function input(event){
      if(!current()||progress)return;
      if(event.target.hasAttribute('data-po-approval-note')){model.approvalNote=event.target.value;return;}
      if(readOnly())return;
      var target=event.target;
      if(target.hasAttribute('data-po-search')){var needle=target.value.toLowerCase(),visible=0;target.parentElement.querySelectorAll('[data-po-pick]').forEach(function(button){button.hidden=(button.dataset.poSearchText||button.textContent.toLowerCase()).indexOf(needle)<0;if(!button.hidden)visible++;});target.parentElement.querySelectorAll('.po-item-group').forEach(function(group){group.hidden=!group.querySelector('[data-po-pick]:not([hidden])');});var empty=target.parentElement.querySelector('[data-po-picker-empty]');if(empty&&target.parentElement.querySelector('[data-po-pick]')){empty.hidden=visible>0;empty.textContent='No matching items.';}return;}
      var fieldName=target.dataset.poField;if(!fieldName)return;
      var line=model.lines.find(function(row){return row.key===target.dataset.key;});
      if(!line){model[fieldName]=target.value;patchTotal();return;}
      line[fieldName]=target.value;
      if(fieldName==='finalAmount'){line.pricingMode='Manual';line.quantity=null;line.unitPrice=null;var row=target.closest('.po-line');for(var f of ['quantity','unitPrice']){var node=row.querySelector('[data-po-field="'+f+'"]');node.value='';node.readOnly=true;}row.querySelector('[data-po-mode]').textContent='Manual amount';row.querySelector('[data-po-calculated]').hidden=false;}
      if(fieldName==='quantity'||fieldName==='unitPrice'){try{line.finalAmount=root.LMPO.multiply(line.quantity,line.unitPrice);}catch(e){line.finalAmount=null;}target.closest('.po-line').querySelector('[data-po-field="finalAmount"]').value=line.finalAmount||'';}
      patchBalances();
      patchTotal();
    }
    async function refresh(){var own=generation;model.balanceState='loading';render();try{var resp=await call({action:'Balances'});if(!current()||generation!==own)return;if(!resp||resp.contract!=='po-v1'||resp.success!==true||!Array.isArray(resp.balances))throw new Error(resp&&resp.error||'Availability cannot be verified.');var seen=new Set();resp.balances.forEach(function(b){if(typeof b.budgetItemId!=='string'||!/^\d+$/.test(b.budgetItemId)||seen.has(b.budgetItemId)||![b.finalCents,b.modCents,b.issuedCents,b.availableCents,b.pendingModificationCents].every(function(n){return typeof n==='string'&&/^-?\d+$/.test(n);}))throw new Error('Malformed budget balance.');seen.add(b.budgetItemId);if(BigInt(b.finalCents)+BigInt(b.modCents)-BigInt(b.issuedCents)!==BigInt(b.availableCents))throw new Error('Budget balance does not reconcile.');});model.balances=resp.balances;model.balanceState='loaded';}catch(e){if(!current()||generation!==own)return;model.balanceState='unavailable';error(e.message);}render();}
    function mountProgress(action){overlay.querySelector('.po-summary').hidden=true;closePopover();progress=true;openedAt=performance.now();card.querySelector('#po-title').textContent=action&&['Approve','Reject','RetryEmail'].includes(action)?(action==='Reject'?'Rejecting':action==='Approve'?'Approving':'Notifying')+' Purchase Order':'Saving Purchase Order';card.querySelector('.po-body').innerHTML='<div class="po-total">'+esc(model.phase)+' → '+esc(model.vendorName||'Vendor')+' · '+money(model.amount)+' · '+model.lines.length+' lines</div><progress max="3" value="1" aria-label="Verified PO save stages"></progress><ol class="po-stages"><li>Validate PO <span>Done</span></li><li>Save PO, lines and modifications <span>Running</span></li><li>Verify PO and approval chain <span>Up next</span></li></ol><div class="po-error" data-po-error role="alert" hidden></div><div data-po-results></div>';card.querySelector('footer').innerHTML='<span data-po-status role="status" aria-live="polite">Saving PO and combined approval…</span><span class="po-spacer"></span><button class="mbtn neutral" data-po-check hidden>Check saved PO</button><button class="mbtn neutral" data-po-done disabled>Close</button>';card.querySelector('[data-po-close]').disabled=true;if(action&&['Approve','Reject','RetryEmail'].includes(action)){var stages=card.querySelectorAll('.po-stages li');['Validate approval decision','Record decision and update chain','Verify PO, mods and notification'].forEach(function(label,i){stages[i].firstChild.textContent=label+' ';});}card.focus();}
    function onState(run,stage){if(!overlay)return;var status=card.querySelector('[data-po-status]');if(!status)return;
      if(stage==='saving'||stage==='checking'){visualBusy=true;status.textContent=stage==='checking'?'Checking saved PO…':(run.decision?'Recording decision and updating chain…':'Saving PO and combined approval…');card.querySelector('[data-po-done]').disabled=true;card.querySelector('[data-po-close]').disabled=true;card.querySelector('[data-po-check]').disabled=true;}
      if(stage==='settled'){
        var wait=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.max(0,1120-(performance.now()-openedAt));
        setTimeout(function(){if(!overlay)return;visualBusy=false;card.querySelector('[data-po-done]').disabled=false;card.querySelector('[data-po-close]').disabled=false;card.querySelector('[data-po-check]').disabled=false;card.querySelector('[data-po-check]').hidden=!run.unknown;card.querySelector('[data-po-done]').textContent=run.snapshot?'Review PO':run.rejected?'Back to draft':'Close';
          var spans=card.querySelectorAll('.po-stages span');spans[1].textContent=run.snapshot?'Done':run.rejected?'Not saved':'Needs review';spans[2].textContent=run.snapshot?'Done':'Needs review';card.querySelector('progress').value=run.snapshot?3:1;
          status.textContent=run.snapshot?(run.snapshot.approvalState==='Approved'?'PO and modifications approved':run.snapshot.approvalState==='Rejected'?'PO rejected · budget reservation retained':run.snapshot.status==='Submitted'?(run.decision?'Approval recorded':'PO submitted · budget reserved')+' · '+(run.snapshot.approvalBundle&&run.snapshot.approvalBundle.emailSent?'Approval email sent':'Approval email needs review'):'Draft saved · no budget reserved'):run.rejected?'PO was not saved':'Saved state is unknown · use read-only Check';error(run.error);
          if(run.snapshot){unresolved[model.budgetId]=null;card.querySelector('[data-po-results]').innerHTML='<ul class="po-results">'+run.snapshot.lines.map(function(line){return '<li>'+tick+'<span>'+esc(line.description)+' · '+money(line.finalAmount)+' · Verified</span></li>';}).concat(run.snapshot.approvalBundle?run.snapshot.approvalBundle.modifications.map(function(mod){return '<li>'+tick+'<span>Budget modification +'+money(mod.amount)+' · '+esc(mod.status)+' · Verified</span></li>';}).concat(run.snapshot.approvalBundle.rows.map(function(row){return '<li>'+tick+'<span>'+esc(row.role)+' approval · '+esc(row.status)+' · Verified</span></li>';})):[]).join('')+'</ul>';options.saved(run.snapshot);}
        },wait);
      }
    }
    async function save(action){if(progress||visualBusy||!current()||readOnly())return;try{
      if(!dateValid(model.requestDate)||!dateValid(model.dateNeeded))throw new Error('Both dates must be valid YYYY-MM-DD dates.');
      model.amount=root.LMPO.currency(totals());
      var payload={action:action,id:model.id||'',expectedRevision:model.revision||'',budgetId:model.budgetId,vendorId:model.vendorId,budgetModificationId:model.budgetModificationId||null,amount:model.amount,requestDate:model.requestDate,dateNeeded:model.dateNeeded,lines:model.lines.map(function(line){return Object.assign({},line,{costCode:lineCode(line)});}),automaticModifications:true,preserveReservation:model.status==='Submitted'&&model.approvalState==='Rejected',token:uid(),userAccessId:options.userAccessId()};root.LMPO.validate(payload,action==='Submit'||payload.preserveReservation);
      if(!model.vendors.some(function(v){return v.ID===model.vendorId;}))throw new Error('Select a verified Vendor.');
      if(action==='Submit'){if(model.balanceState!=='loaded')throw new Error('Refresh and verify budget availability before submitting.');var v=root.LMPO.validate(payload,true);for(var key of Object.keys(v.grouped)){var b=model.balances.find(function(row){return row.budgetItemId===key;});if(!b)throw new Error('A selected item has no verified balance.');}}
      if(action==='Submit'){payload.expectedBalances={};payload.expectedPendingModifications={};allocationRows().forEach(function(row){if(!row.verified)throw new Error('Item balance is unverified.');payload.expectedBalances[row.budgetItemId]=String(row.available);payload.expectedPendingModifications[row.budgetItemId]=String(row.pending);});}
      mountProgress();await controller.begin(payload);
    }catch(e){error(e.message);}}
    async function savedList(){var own=generation;try{var resp=await call({action:'List'});if(!current()||own!==generation)return;if(resp.contract!=='po-v1'||!resp.success||!Array.isArray(resp.rows))throw new Error(resp.error||'Saved POs unavailable.');overlay.querySelector('.po-summary').hidden=true;card.querySelector('.po-body').innerHTML='<div data-po-error class="po-error" role="alert" hidden></div><div class="po-saved-list">'+resp.rows.map(function(row){if(typeof row.id!=='string'||!/^\d+$/.test(row.id))throw new Error('Invalid PO ID.');return '<button class="mbtn neutral" data-po-open="'+esc(row.id)+'">'+money(row.amount)+' · '+esc(row.status)+'</button>';}).join('')+'</div>';card.querySelector('footer').innerHTML='<button class="mbtn neutral" data-po-back>Back to draft</button>';}catch(e){error(e.message);}}
    async function get(id){var own=generation;try{var resp=await call({action:'Get',id:id});if(!current()||own!==generation)return;if(!resp||resp.contract!=='po-v1'||!resp.success||!resp.snapshot||resp.snapshot.id!==id||resp.snapshot.budgetId!==model.budgetId)throw new Error(resp&&resp.error||'PO could not be loaded.');if(!['Draft','Submitted'].includes(resp.snapshot.status)||resp.snapshot.commitmentState!==(resp.snapshot.status==='Submitted'?'Reserved':'None')||!['Not Configured','Pending','Approved','Rejected'].includes(resp.snapshot.approvalState))throw new Error('Saved PO state could not be verified.');root.LMPO.validate(Object.assign({},resp.snapshot,{lines:resp.snapshot.lines.map(function(line){return Object.assign({},line,{uom:line.uom||"EA"});})}),resp.snapshot.status==='Submitted');Object.assign(model,resp.snapshot);model.reservedLines=resp.snapshot.commitmentState==='Reserved'?resp.snapshot.lines.map(function(l){return Object.assign({},l);}):[];render();refresh();}catch(e){error(e.message);}}
    function click(event){if(popover&&!popover.element.contains(event.target)&&!popover.trigger.contains(event.target)){closePopover();}var target=event.target.closest('button,input[data-po-date]');if(!target)return;
      if(target.hasAttribute('data-po-pop-close')){closePopover();return;}
      if(target.hasAttribute('data-po-close')){close();return;}
      if(target.hasAttribute('data-po-done')){var run=controller.state();if(run&&run.snapshot){Object.assign(model,run.snapshot);model.reservedLines=run.snapshot.commitmentState==='Reserved'?run.snapshot.lines.map(function(l){return Object.assign({},l);}):[];progress=false;render();refresh();return;}if(run&&run.rejected){progress=false;render();return;}close();return;}
      if(target.hasAttribute('data-po-check')){if(!visualBusy){openedAt=performance.now();controller.check();}return;}
      if(progress||!current())return;
      if(target.dataset.poDecision){decide(target.dataset.poDecision).catch(function(e){error(e.message);});return;}
      if(target.hasAttribute('data-po-saved')){savedList();return;}if(target.dataset.poOpen){get(target.dataset.poOpen);return;}if(target.hasAttribute('data-po-back')){render();return;}if(target.hasAttribute('data-po-refresh')){refresh();return;}
      if(readOnly())return;
      if(target.dataset.poDate){event.stopPropagation();openDate(target);return;}
      if(target.dataset.poPicker){openPopover(target);return;}
      if(target.dataset.poSave){save(target.dataset.poSave);return;}if(target.hasAttribute('data-po-add')){var count=Math.min(Number(target.dataset.poAdd)||1,100-model.lines.length),last=model.lines[model.lines.length-1];for(var add=0;add<count;add++){var next=lineNew();if(last){next.budgetItemId=last.budgetItemId;next.uom=last.uom;}model.lines.push(next);}render();return;}
      if(target.dataset.poDuplicate){if(model.lines.length>=100){error('A PO can have at most 100 lines.');return;}var index=model.lines.findIndex(function(line){return line.key===target.dataset.poDuplicate;});if(index<0)return;var copy=root.LMPO.duplicate(model.lines[index],uid());model.lines.splice(index+1,0,copy);render();var input=card.querySelector('[data-line="'+copy.key+'"] [data-po-field=description]');input.focus();input.select();return;}
      if(target.dataset.poRemove){model.lines=model.lines.filter(function(line){return line.key!==target.dataset.poRemove;});render();return;}
      if(target.dataset.poCalculated){var at=model.lines.findIndex(function(l){return l.key===target.dataset.poCalculated;});model.lines[at]=root.LMPO.calculated(model.lines[at]);render();return;}
      if(target.dataset.poPick){var line=model.lines.find(function(l){return l.key===target.dataset.key;});(line||model)[target.dataset.poPick]=target.dataset.value;if(target.dataset.poPick==='vendorId')model.vendorName=target.textContent;if(line&&target.dataset.poPick==='budgetItemId'&&!line.description){var item=options.items().find(function(i){return i.ID===line.budgetItemId;});line.description=item&&(item.Item_Name||item.Description)||'';}closePopover();render();return;}

    }
    async function open(budget,source,purchaseOrderId){if(overlay)return;trigger=source||document.activeElement;generation++;var pending=unresolved[String(budget.ID)];
      if(pending){if(pending.model.scope!==options.scope())throw new Error('An unresolved PO belongs to another Creator session. Review that operation before opening a new draft.');model=pending.model;controller=pending.controller;mount();mountProgress();onState(controller.state(),'settled');return;}
      model={budgetId:String(budget.ID),phase:options.phaseName(budget),scope:options.scope(),editable:options.canEdit(budget),amount:'',reservedLines:[],vendorId:'',budgetModificationId:null,modifications:options.modifications?options.modifications():[],requestDate:localDate(new Date()),dateNeeded:'',lines:[lineNew()],vendors:[],balances:[],balanceState:'loading',error:''};
      controller=root.LMPOController.create({call:call,onState:onState});mount();render();var own=generation;
      try{var vendors=await options.vendors();if(!current()||own!==generation)return;var seen=new Set();vendors.forEach(function(row){if(typeof row.ID!=='string'||!/^\d+$/.test(row.ID)||seen.has(row.ID))throw new Error('Vendor identity is unavailable.');seen.add(row.ID);});model.vendors=vendors;render();}catch(e){if(current())error(e.message);}
      if(current()){if(purchaseOrderId)await get(String(purchaseOrderId));else refresh();}
    }
    return {open:open,isOpen:function(){return !!overlay;}};
  }
  root.LMPOUI={create:create};
})(typeof globalThis!=="undefined"?globalThis:this);
