(function(root){
  'use strict';
  var closeIcon='<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 6l12 12M18 6L6 18"/></svg>';
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function copy(v){return JSON.parse(JSON.stringify(v));}
  function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(function(key){return [key,stable(value[key])];}));return value;}
  function equal(a,b){return JSON.stringify(stable(a))===JSON.stringify(stable(b));}
  function verify(receipt,run){if(!receipt||receipt.contract!=='approval-policy-v1'||receipt.success!==true||receipt.writeState!=='verified'||receipt.token!==run.token||!receipt.after||typeof receipt.after.id!=='string'||!/^\d+$/.test(receipt.after.id))throw new Error('Configuration write was not verified.');if(run.data.id&&receipt.after.id!==run.data.id)throw new Error('Another configuration record was returned.');if(run.action==='Publish'&&receipt.after.status!=='Published')throw new Error('Publication was not verified.');if(run.action==='SavePolicy'&&(receipt.after.status!=='Draft'||receipt.after.adapterEnabled!==false))throw new Error('Draft policy state was not verified.');return receipt.after;}
  function create(options){
    var panel=null,card=null,config=null,tab='Policies',draft=null,editing='',inert=[],trigger=null,pending=null,busy=false,scope='',epoch=0;
    function same(){return options.scope()===scope;}
    function msg(text){var node=card.querySelector('[data-ap-error]');if(node){node.hidden=!text;node.textContent=text;}}
    function picker(label,field,value,rows,index){var selected=rows.find(function(row){return row.id===value;});return '<label>'+esc(label)+'<details><summary>'+esc(selected?selected.label:'Choose…')+'</summary><div class="ap-options"><input data-ap-search placeholder="Search" aria-label="Search '+esc(label)+'"><div>'+rows.map(function(row){return '<button data-ap-pick="'+field+'" data-index="'+(index==null?'':index)+'" data-value="'+esc(row.id)+'">'+esc(row.label)+'</button>';}).join('')+'</div></div></details></label>';}
    function choices(values){return values.map(function(v){return {id:v,label:v};});}
    function field(label,key,value,index){return '<label>'+esc(label)+'<input data-ap-field="'+key+'" data-index="'+(index==null?'':index)+'" value="'+esc(value)+'"></label>';}
    function check(label,key,value,index){return '<label class="ap-check"><input type="checkbox" data-ap-field="'+key+'" data-index="'+(index==null?'':index)+'" '+(value===true?'checked':'')+'>'+esc(label)+'</label>';}
    function companies(){return config.companies;}
    function territories(){return [{id:'',label:'Company default'}].concat(config.territories);}
    function departments(){return [{id:'',label:'All departments'}].concat(choices(['Development','Construction','Engineering','Surveying']));}
    function roleRows(){return config.roles.map(function(row){return {id:row.id,label:row.name+(row.active?'':' · Inactive')};});}
    function userRows(){return config.users.map(function(row){return {id:row.id,label:(row.name||row.user)+(row.routingEnabled?'':' · Routing disabled')};});}
    function scopeFields(data){return picker('Company','companyId',data.companyId,companies())+picker('Territory','territory',data.territory||'',territories())+picker('Department','department',data.department||'',departments());}
    function render(){if(!panel||pending)return;card.querySelector('.ap-body').innerHTML='<div data-ap-error role="alert" class="ap-error" hidden></div>'+(!config?'<p>Loading approvals…</p>':draft?editor():listing());card.querySelector('.ap-tabs').innerHTML=['Roles','Assignments','Policies','Preview','Audit'].map(function(t){return '<button data-ap-tab="'+t+'" class="'+(tab===t?'active':'')+'">'+t+'</button>';}).join('');card.querySelector('footer').innerHTML=draft?'<button class="btn" data-ap-cancel>Cancel</button><span class="ap-spacer"></span><button class="btn" data-ap-save>'+ (editing==='Preview'?'Preview route':'Save draft')+'</button>':'<button class="btn" data-ap-refresh>Refresh</button><span class="ap-spacer"></span>'+(['Roles','Assignments','Policies'].includes(tab)?'<button class="btn" data-ap-new>New '+(tab==='Assignments'?'assignment':tab==='Policies'?'policy':'role')+'</button>':'');}
    function listing(){
      if(tab==='Preview'){newDraft('Preview');return editor();}
      if(tab==='Audit')return '<div class="ap-list">'+(config.audit||[]).slice().reverse().slice(0,50).map(function(row){return '<div><strong>'+esc(row.action)+'</strong><span>'+esc(row.status)+' · '+esc(row.actorName||row.actorId)+'</span><details><summary>Change details</summary><strong>Before</strong><pre>'+esc(JSON.stringify(row.before||{},null,2))+'</pre><strong>After</strong><pre>'+esc(JSON.stringify(row.after||row.intended||{},null,2))+'</pre></details></div>';}).join('')+'</div>';
      var rows=tab==='Roles'?config.roles:tab==='Assignments'?config.assignments:config.policies;
      return '<div class="ap-list">'+rows.map(function(row){var title=tab==='Roles'?row.name:tab==='Assignments'?(config.roles.find(function(r){return r.id===row.roleId;})||{}).name:(row.workflow+' · v'+row.version);var detail=tab==='Policies'?row.status:row.active?'Active':'Inactive';return '<div><strong>'+esc(title)+'</strong><span>'+esc(detail)+' '+esc(row.territory||'Company default')+'</span><button class="btn" data-ap-edit="'+esc(row.id)+'">'+(row.status==='Published'?'New version':'Edit')+'</button>'+(row.status==='Draft'?'<button class="btn" data-ap-publish="'+esc(row.id)+'">Publish</button>':'')+(row.status==='Published'?'<button class="btn" data-ap-retire="'+esc(row.id)+'">End effective window</button>':'')+'</div>';}).join('')+'</div><p class="muted">Precedence: territory + department → territory → company + department → company.</p>';
    }
    function newDraft(kind){editing=kind;draft=kind==='Roles'?{id:'',name:'',active:false}:kind==='Assignments'?{id:'',roleId:'',companyId:'',territory:'',department:'',userAccessId:'',active:false,effectiveFrom:'',effectiveTo:''}:kind==='Preview'?{workflow:'',companyId:'',territory:'',department:'',submitterId:'',amount:'',effectiveDate:new Date().toISOString().slice(0,10)}:{id:'',companyId:'',workflow:'',territory:'',department:'',version:1,status:'Draft',enabled:false,selfApproval:'Unspecified',duplicatePerson:'Unspecified',effectiveFrom:'',effectiveTo:'',steps:[],adapterEnabled:false};}
    function editor(){
      var html='<div class="ap-grid">';
      if(editing==='Roles')return html+field('Role name','name',draft.name)+check('Active','active',draft.active)+'</div>';
      if(editing==='Retire')return html+field('Exclusive end date (YYYY-MM-DD)','effectiveTo',draft.effectiveTo)+'</div>';
      if(editing==='Assignments')return html+picker('Role','roleId',draft.roleId,roleRows())+scopeFields(draft)+picker('Person (User Access)','userAccessId',draft.userAccessId,userRows())+field('Effective from (YYYY-MM-DD)','effectiveFrom',draft.effectiveFrom)+field('Effective to (exclusive)','effectiveTo',draft.effectiveTo)+check('Active','active',draft.active)+'</div>';
      html+=picker('Workflow','workflow',draft.workflow,choices(['Budget','Budget Modification','Pro Forma','Contract','Purchase Order']))+scopeFields(draft);
      if(editing==='Preview')return html+picker('Submitter','submitterId',draft.submitterId,userRows())+(['Pro Forma','Contract'].includes(draft.workflow)?'':field(draft.workflow==='Purchase Order'?'Full header amount':'Submitted amount','amount',draft.amount))+field('Effective date (YYYY-MM-DD)','effectiveDate',draft.effectiveDate)+(draft.workflow==='Purchase Order'?check('Budget modification linked to this PO','hasBudgetModification',draft.hasBudgetModification)+check('At least one PO budget item exceeds available budget','hasBudgetOverrun',draft.hasBudgetOverrun):'')+'</div><div data-ap-route></div>';
      html+=field('Version','version',draft.version)+field('Effective from (YYYY-MM-DD)','effectiveFrom',draft.effectiveFrom)+field('Effective to (exclusive)','effectiveTo',draft.effectiveTo)+picker('Submitter self-approval','selfApproval',draft.selfApproval,choices(draft.workflow==='Purchase Order'?['Deny']:['Unspecified','Allow','Deny']))+picker('One person in multiple roles','duplicatePerson',draft.duplicatePerson,choices(draft.workflow==='Purchase Order'?['Reject']:['Unspecified','Separate steps','Reject']))+check('Policy enabled','enabled',draft.enabled)+'</div><h3>Ordered steps</h3><div class="ap-steps">';
      html+=draft.steps.map(function(step,index){return '<article><strong>Step '+(index+1)+'</strong><div class="ap-grid">'+picker('Role','roleId',step.roleId,roleRows(),index)+picker('Condition','condition',step.condition,choices(['Pro Forma','Contract'].includes(draft.workflow)?['Always']:['Always','Above','At or above'].concat(draft.workflow==='Purchase Order'?['Budget modification attached','Budget line exceeded']:[])),index)+((step.condition==='Above'||step.condition==='At or above')?field('Threshold','threshold',step.threshold,index):'')+check('Enabled','enabled',step.enabled,index)+'</div><button class="btn" data-ap-up="'+index+'" '+(index===0?'disabled':'')+'>Move up</button> <button class="btn" data-ap-down="'+index+'" '+(index===draft.steps.length-1?'disabled':'')+'>Move down</button> <button class="btn" data-ap-remove="'+index+'">Remove step</button></article>';}).join('');
      return html+'</div><button class="btn" data-ap-step>Add step</button>';
    }
    async function load(){var own=epoch;try{var response=await options.call({action:'List'});if(!panel||own!==epoch||!same())return;if(!response||response.contract!=='approval-policy-v1'||response.success!==true||!response.configuration||response.canAdmin!==true)throw new Error(response&&response.error||'Approval administration is unavailable.');config=response.configuration;for(var key of ['roles','assignments','policies','users','companies','territories'])if(!Array.isArray(config[key]))throw new Error('Configuration read was incomplete.');render();}catch(e){if(panel&&own===epoch){render();msg(e.message);card.querySelectorAll('footer button').forEach(function(b){b.disabled=true;});}}}
    function progress(){card.querySelector('.ap-tabs').hidden=true;card.querySelector('.ap-body').innerHTML='<div data-ap-error role="alert" class="ap-error" hidden></div><progress max="3" value="1" aria-label="Verified configuration stages"></progress><ol><li>Validate configuration <span>Done</span></li><li>Save and audit change <span>Running</span></li><li>Verify saved configuration <span>Up next</span></li></ol><div data-ap-results></div>';card.querySelector('footer').innerHTML='<span data-ap-status role="status" aria-live="polite">Saving configuration…</span><span class="ap-spacer"></span><button class="btn" data-ap-check hidden>Check saved change</button><button class="btn" data-ap-done disabled>Done</button>';card.querySelector('[data-ap-close]').disabled=true;card.focus();}
    async function commit(action,data){if(pending||busy||!same())return;try{
      if(action==='SavePolicy')root.LMApprovalPolicy.validatePolicy(Object.assign({},data,{id:data.id||'1',selfApproval:data.selfApproval==='Unspecified'?'Deny':data.selfApproval,duplicatePerson:data.duplicatePerson==='Unspecified'?'Reject':data.duplicatePerson}));
      if(action==='Publish'){var candidate=config.policies.find(function(p){return p.id===data.id;});if(!candidate)throw new Error('Draft policy was not found.');root.LMApprovalPolicy.assertPublish(candidate,config.policies);}
      if(action==='SaveRole'&&!data.name.trim())throw new Error('Role name is required.');
      if(action==='SaveAssignment'&&(!data.roleId||!data.userAccessId||!data.companyId))throw new Error('Choose role, company and User Access person.');
      pending={action:action,data:copy(data),token:crypto.randomUUID(),unknown:false};progress();await send(false);
    }catch(e){msg(e.message);}}
    async function send(check){if(busy||!pending||!same())return;busy=true;var started=performance.now(),timer;card.querySelector('[data-ap-done]').disabled=true;card.querySelector('[data-ap-close]').disabled=true;card.querySelector('[data-ap-check]').disabled=true;try{
      var payload=check?{action:'Check',token:pending.token}:pending;
      var response=await Promise.race([options.call(payload),new Promise(function(resolve,reject){timer=setTimeout(function(){reject(new Error('Response was lost. Check saved configuration before any further write.'));},90000);})]);
      if(response&&response.contract==='approval-policy-v1'&&response.writeState==='not-started'&&!check){pending.rejected=true;pending.error=response.error||'Change was not saved.';}
      else {pending.after=verify(response,pending);pending.unknown=false;pending.error='';}
    }catch(e){pending.unknown=true;pending.error=e.message;}finally{clearTimeout(timer);var wait=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.max(0,1120-(performance.now()-started));setTimeout(function(){if(!panel)return;busy=false;card.querySelector('[data-ap-done]').disabled=false;card.querySelector('[data-ap-close]').disabled=false;card.querySelector('[data-ap-check]').disabled=false;card.querySelector('[data-ap-check]').hidden=!pending.unknown;card.querySelector('[data-ap-status]').textContent=pending.after?'Configuration verified':pending.rejected?'Change was not saved':'Saved state is unknown';card.querySelector('progress').value=pending.after?3:1;var chips=card.querySelectorAll('ol span');chips[1].textContent=pending.after?'Done':'Needs review';chips[2].textContent=pending.after?'Done':'Needs review';msg(pending.error);if(pending.after)card.querySelector('[data-ap-results]').textContent=(pending.action==='Publish'?'Policy published':'Configuration saved')+' · verified audit receipt';},wait);}}
    async function preview(){if(busy||!same())return;busy=true;card.querySelector('[data-ap-save]').disabled=true;try{var context=copy(draft);if(['Pro Forma','Contract'].includes(context.workflow))delete context.amount;else context.amount=root.LMApprovalPolicy.currency(context.amount);var response=await options.call({action:'Preview',context:context});if(!panel||!same())return;if(!response||response.contract!=='approval-policy-v1'||response.success!==true||!response.snapshot)throw new Error(response&&response.error||'Route could not be resolved.');var local=root.LMApprovalPolicy.resolve(config,context);if(!equal(local.route,response.snapshot.route)||!equal(local.excluded,response.snapshot.excluded)||local.policyId!==response.snapshot.policyId||local.policyVersion!==response.snapshot.policyVersion)throw new Error('Server route differs from this configuration snapshot. Refresh before continuing.');card.querySelector('[data-ap-route]').innerHTML='<h3>Policy version '+esc(local.policyVersion)+'</h3><ol>'+local.route.map(function(step){return '<li><strong>'+esc(step.role)+' · '+esc(step.name||step.userAccessId)+'</strong><span>'+esc(step.email)+' · '+esc(step.reason)+'</span></li>';}).join('')+'</ol>'+local.excluded.map(function(step){return '<div class="muted">'+esc(step.key)+' · '+esc(step.reason)+'</div>';}).join('');}catch(e){msg(e.message);}finally{busy=false;if(panel&&card.querySelector('[data-ap-save]'))card.querySelector('[data-ap-save]').disabled=false;}}
    function input(event){if(!draft||pending||busy)return;var el=event.target;if(el.hasAttribute('data-ap-search')){var search=el.value.toLowerCase();el.parentElement.querySelectorAll('button').forEach(function(b){b.hidden=b.textContent.toLowerCase().indexOf(search)<0;});return;}if(el.dataset.apField){var data=el.dataset.index!==''?draft.steps[Number(el.dataset.index)]:draft;data[el.dataset.apField]=el.type==='checkbox'?el.checked:el.dataset.apField==='version'?Number(el.value):el.value;}}
    function click(event){var el=event.target.closest('button');if(!el)return;
      if(el.hasAttribute('data-ap-close')){close();return;}
      if(el.hasAttribute('data-ap-check')){send(true);return;}
      if(el.hasAttribute('data-ap-done')){if(busy)return;if(pending.unknown){close();return;}pending=null;draft=null;card.querySelector('.ap-tabs').hidden=false;render();load();return;}
      if(pending||busy||!same())return;
      if(el.dataset.apTab){tab=el.dataset.apTab;draft=null;render();return;}if(el.hasAttribute('data-ap-refresh')){load();return;}if(el.hasAttribute('data-ap-new')){newDraft(tab);render();return;}if(el.hasAttribute('data-ap-cancel')){draft=null;render();return;}
      if(el.dataset.apEdit){var rows=tab==='Roles'?config.roles:tab==='Assignments'?config.assignments:config.policies;draft=copy(rows.find(function(row){return row.id===el.dataset.apEdit;}));editing=tab;if(draft.status==='Published'){draft.id='';draft.version++;draft.status='Draft';draft.adapterEnabled=false;}render();return;}
      if(el.dataset.apPublish){commit('Publish',{id:el.dataset.apPublish});return;}
      if(el.dataset.apRetire){draft={id:el.dataset.apRetire,effectiveTo:''};editing='Retire';render();return;}
      if(el.dataset.apPick){var data=el.dataset.index!==''?draft.steps[Number(el.dataset.index)]:draft;data[el.dataset.apPick]=el.dataset.value;if(el.dataset.apPick==='workflow'&&['Pro Forma','Contract'].includes(el.dataset.value)){if(draft.steps)draft.steps.forEach(function(step){step.condition='Always';step.threshold='';});delete draft.amount;}if(el.dataset.apPick==='workflow'&&el.dataset.value==='Purchase Order'){draft.hasBudgetModification=false;draft.hasBudgetOverrun=false;if(editing!=='Preview'){draft.selfApproval='Deny';draft.duplicatePerson='Reject';}}render();return;}
      if(el.hasAttribute('data-ap-step')){if(draft.steps.length<30)draft.steps.push({key:crypto.randomUUID(),order:draft.steps.length+1,roleId:'',condition:'Always',threshold:'',enabled:true});render();return;}
      if(el.hasAttribute('data-ap-remove')){draft.steps.splice(Number(el.dataset.apRemove),1);draft.steps.forEach(function(step,i){step.order=i+1;});render();return;}
      if(el.hasAttribute('data-ap-up')||el.hasAttribute('data-ap-down')){var index=Number(el.dataset.apUp||el.dataset.apDown),to=index+(el.hasAttribute('data-ap-up')?-1:1);var step=draft.steps.splice(index,1)[0];draft.steps.splice(to,0,step);draft.steps.forEach(function(step,i){step.order=i+1;});render();return;}
      if(el.hasAttribute('data-ap-save')){if(editing==='Preview')preview();else commit(editing==='Roles'?'SaveRole':editing==='Assignments'?'SaveAssignment':editing==='Retire'?'Retire':'SavePolicy',draft);}
    }
    function close(){if(busy)return;if(pending&&!pending.unknown){pending=null;draft=null;}epoch++;panel.remove();panel=null;inert.forEach(function(pair){pair[0].inert=pair[1];});if(trigger&&trigger.isConnected)trigger.focus();}
    function keydown(event){if(event.key==='Escape'){event.preventDefault();close();return;}if(event.key==='Tab'){var nodes=Array.from(card.querySelectorAll('button:not(:disabled),input:not(:disabled),summary')).filter(function(n){return n.getClientRects().length;});if(!nodes.length){event.preventDefault();card.focus();return;}if(event.shiftKey&&(document.activeElement===nodes[0]||document.activeElement===card)){event.preventDefault();nodes[nodes.length-1].focus();}else if(!event.shiftKey&&document.activeElement===nodes[nodes.length-1]){event.preventDefault();nodes[0].focus();}}}
    function open(){if(panel)return;var next=options.scope();if(pending&&scope!==next)throw new Error('Previous configuration operation belongs to another session. Review it before proceeding.');scope=next;epoch++;trigger=document.activeElement;panel=document.createElement('div');panel.className='ap-overlay';panel.innerHTML='<section class="ap-card" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="ap-title"><header><h2 id="ap-title">Approvals</h2><button class="ap-x" data-ap-close aria-label="Close Approvals">'+closeIcon+'</button></header><nav class="ap-tabs"></nav><div class="ap-body"></div><footer></footer></section>';document.body.appendChild(panel);card=panel.querySelector('.ap-card');inert=Array.from(document.body.children).filter(function(n){return n!==panel&&n.tagName!=='SCRIPT'&&n.tagName!=='STYLE';}).map(function(n){var old=n.inert;n.inert=true;return [n,old];});panel.addEventListener('click',click);panel.addEventListener('input',input);panel.addEventListener('keydown',keydown);card.focus();if(pending){progress();card.querySelector('[data-ap-check]').hidden=false;card.querySelector('[data-ap-done]').disabled=false;card.querySelector('[data-ap-close]').disabled=false;msg(pending.error);card.querySelector('[data-ap-status]').textContent='Saved state is unknown · use read-only Check';}else{render();load();}}
    return {open:open};
  }
  root.LMApprovalAdmin={create:create,verify:verify,equal:equal};
})(typeof globalThis!=='undefined'?globalThis:this);
